services:
  # Web service for API endpoints
  - type: web
    name: snipnote-transcription
    env: python
    buildCommand: |
      chmod +x install_ffmpeg.sh
      ./install_ffmpeg.sh
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: API_KEY
        sync: false

  # Cron job for background worker
  - type: cron
    name: snipnote-transcription-worker
    env: python
    schedule: "* * * * *"  # Run every 1 minute for faster response
    buildCommand: |
      chmod +x install_ffmpeg.sh
      ./install_ffmpeg.sh
      pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
